package capaPresentacion;

/**
 * Clase Principal. En esta clase dentro del nivel de presentacion se va a
 * mostrar y recibir los datos al usuario final (o cliente). Al unico que vamos
 * a llamar es a la capaNegocio, ya que la capaPresentacion NO SE DEBE comunicar
 * directamente con la capaPersistencia.
 *
 * @author suNombre
 * @since Octubre 2020
 * @version 1.0
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelABMC = new javax.swing.JTabbedPane();
        panelAGREGAR = new javax.swing.JPanel();
        panelMODIFICAR = new javax.swing.JPanel();
        panelDARBAJA = new javax.swing.JPanel();
        panelMOSTRAR = new javax.swing.JPanel();
        panelFILTRAR = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        opcionMenu = new javax.swing.JMenu();
        opcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelABMC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout panelAGREGARLayout = new javax.swing.GroupLayout(panelAGREGAR);
        panelAGREGAR.setLayout(panelAGREGARLayout);
        panelAGREGARLayout.setHorizontalGroup(
            panelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        panelAGREGARLayout.setVerticalGroup(
            panelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        panelABMC.addTab("AGREGAR", panelAGREGAR);

        javax.swing.GroupLayout panelMODIFICARLayout = new javax.swing.GroupLayout(panelMODIFICAR);
        panelMODIFICAR.setLayout(panelMODIFICARLayout);
        panelMODIFICARLayout.setHorizontalGroup(
            panelMODIFICARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        panelMODIFICARLayout.setVerticalGroup(
            panelMODIFICARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        panelABMC.addTab("MODIFICAR", panelMODIFICAR);

        javax.swing.GroupLayout panelDARBAJALayout = new javax.swing.GroupLayout(panelDARBAJA);
        panelDARBAJA.setLayout(panelDARBAJALayout);
        panelDARBAJALayout.setHorizontalGroup(
            panelDARBAJALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        panelDARBAJALayout.setVerticalGroup(
            panelDARBAJALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        panelABMC.addTab("DAR BAJA", panelDARBAJA);

        javax.swing.GroupLayout panelMOSTRARLayout = new javax.swing.GroupLayout(panelMOSTRAR);
        panelMOSTRAR.setLayout(panelMOSTRARLayout);
        panelMOSTRARLayout.setHorizontalGroup(
            panelMOSTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        panelMOSTRARLayout.setVerticalGroup(
            panelMOSTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        panelABMC.addTab("MOSTRAR ESTUDIANTES", panelMOSTRAR);

        javax.swing.GroupLayout panelFILTRARLayout = new javax.swing.GroupLayout(panelFILTRAR);
        panelFILTRAR.setLayout(panelFILTRARLayout);
        panelFILTRARLayout.setHorizontalGroup(
            panelFILTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        panelFILTRARLayout.setVerticalGroup(
            panelFILTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        panelABMC.addTab("FILTRAR", panelFILTRAR);

        opcionMenu.setText("Menu");

        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        opcionMenu.add(opcionSalir);

        menuBar.add(opcionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelABMC)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelABMC)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_opcionSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu opcionMenu;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JTabbedPane panelABMC;
    private javax.swing.JPanel panelAGREGAR;
    private javax.swing.JPanel panelDARBAJA;
    private javax.swing.JPanel panelFILTRAR;
    private javax.swing.JPanel panelMODIFICAR;
    private javax.swing.JPanel panelMOSTRAR;
    // End of variables declaration//GEN-END:variables
}
